name: Deploy to Google Cloud Run
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GCP_REGION }}
  SERVICE: video-vault  # Changed to match your existing setup
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          registry: '${{ secrets.GCP_REGION }}-docker.pkg.dev'
          username: _json_key
          password: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Build and Push Container
        run: |-
          docker build -t "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}"
          
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}
          flags: '--allow-unauthenticated --port=8080 --memory=4Gi --timeout=600 --concurrency=1 --max-instances=1'
          env_vars: |
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}
            
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}